services:
  #db:
  #  image: postgres:17
  #  user: root
  #  environment:
  #    - POSTGRES_USER=xecohil
  #    - POSTGRES_PASSWORD=Chucam2022++
  #    - POSTGRES_DB=choltzij
  #  restart: always             # run as a service
  #  volumes:
  #      - ./postgresql:/var/lib/postgresql/data

  odoo18:
    image: odoo:18
    user: root
    #depends_on:
    #  - db
    ports:
      - "10018:8069"
      - "20018:8072" # live chat
    tty: true
    command: --
    environment:
      - DB_PORT_5432_TCP_ADDR=168.231.73.120
      - DB_PORT_5432_TCP_PORT=5432
      - DB_ENV_POSTGRES_USER=xecohil
      - DB_ENV_POSTGRES_DATABASE=choltzij
      - DB_ENV_POSTGRES_PASSWORD=Chucam2022++
      - PIP_BREAK_SYSTEM_PACKAGES=1
      #- HOST=168.231.73.120
      #- USER=xecohil
      #- PASSWORD=Chucam2022++
      #- PIP_BREAK_SYSTEM_PACKAGES=1
      #- DATABASE=Chucam2022++
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      - ./entrypoint.sh:/entrypoint.sh
      - ./wait-for-psql.py:/wait-for-psql.py
      #- ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo:rw
      - /mnt/user/appdata/odoo/data:/var/lib/odoo:rw
      - /mnt/user/appdata/odoo/config:/etc/odoo:rw
      - /mnt/user/appdata/odoo/addons:/mnt/extra-addons:rw
    networks:
      - choltzij-backend-dfidru_default
    labels:
      - traefik.http.routers.choltzij-backend-dfidru_default-web.rule=Host(`choltzij-odoo-d039d4-168-231-73-120.traefik.me`)
      - traefik.http.routers.choltzij-backend-dfidru_default-8-web.entrypoints=odoo18
      - traefik.http.services.choltzij-backend-dfidru_default-8-web.loadbalancer.server.port=10018
      - traefik.http.routers.choltzij-backend-dfidru_default-8-web.service=choltzij-backend-dfidru_default-8-web
      - traefik.enable=true
    restart: always             # run as a service
volumes:
  odoo-web-data-choltzij-backend-dfidru_default: null
  odoo-db-data-choltzij-backend-dfidru_default: null
networks:
  choltzij-backend-dfidru_default:
    name: choltzij-backend-dfidru_default
    external: true
